# Generated by Django 5.2.7 on 2026-05-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'firearm', 'verbose_name_plural': 'firearms'},
        ),
        migrations.AlterModelOptions(
            name='orgmember',
            options={'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'caliber', 'verbose_name_plural': 'calibers'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AddField(
            model_name='organization',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price (USD)'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=150, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentorg.college', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250, verbose_name='firearm name'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(verbose_name='sale date'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.organization', verbose_name='firearm'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.student', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='program',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.college', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(max_length=150, verbose_name='caliber / series'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=25, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.program', verbose_name='preferred caliber'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=15, verbose_name='customer ID'),
        ),
    ]
